# Create schemas

# Create tables
CREATE TABLE IF NOT EXISTS PLAYERS
(
    UUID VARCHAR(100) NOT NULL,
    NAME VARCHAR(50),
    EXP INT,
    MONEY INT,
    RANK VARCHAR(20),
	KILLS INT,
	DEATHS INT,
    PRIMARY KEY(UUID)
);

CREATE TABLE IF NOT EXISTS Mobs
(
    UUID VARCHAR(100) NOT NULL,
    MOB VARCHAR(50),
    EXP INT,
    TIER INT,
	KILLS INT,
	DEATHS INT,
    PRIMARY KEY(UUID)
);
